config/routes.rb
Rails.application.routes.draw do
  get 'colleges', to: 'schools#index'
  get 'bootcamps', to: 'bootcamps#bootcamps'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'schools#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :school_extras
  validates_formatting_of :url, using: :url
  validates_presence_of :name, :url, :degree, :program
  validates_uniqueness_of :url
  validates_inclusion_of  :degree, :in => %w( Masters Bachelors Doctorate Certificate )
  
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/school_extra.rb
class SchoolExtra < ActiveRecord::Base
  belongs_to :school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
  end
end

app/controllers/bootcamps_controller.rb
class BootcampsController < ApplicationController
  def bootcamps
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
    respond_to do |format|
      format.html
      format.json { render text: @schools.to_json }
      format.csv { render text: @schools.to_csv }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/application/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Welcome to Data Science Community</h1>
    
    
    <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<div id="mc_embed_signup">
<form action="<%='//community.us7.list-manage.com/subscribe/post?u=' + (Rails.env.production? ? ENV['MC_KEY'] : 'abc') + '&amp;id=' + (Rails.env.production? ? ENV['MC_ID'] : 'abc')%>" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	<label for="mce-EMAIL">Data Science Community Newsletter</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="<%='b_' + (Rails.env.production? ? ENV['MC_KEY'] : 'abc') + '_' + (Rails.env.production? ? ENV['MC_ID'] : 'abc')%>" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->
  </div>
</div>

app/views/bootcamps/bootcamps.html.erb
<h1>Coming Really Soon....I bet you are excited</h1>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Data Science Community", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Colleges", defined?(colleges_path) ? colleges_path : "#" %></li>
        <li><%= link_to "Bootcamps", defined?(bootcamps_path) ? bootcamps_path : "#" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Data Science Community</title>
    <meta name="description" content="data science, college, university">
    <meta name="author" content="Ryan Swanstrom">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/><!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? %>
  <!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.2/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>

  </head> 
<body>
  <%= render partial: "elements/navbar" %>
  <%= bootstrap_flash %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/schools/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Colleges and Universities with Data Science Degrees</h1>
    <p>
      <div class="pw-widget pw-counter-horizontal">
        <a class="pw-button-facebook pw-look-native"></a>
        <a class="pw-button-twitter pw-look-native"></a>
        <a class="pw-button-linkedin pw-look-native"></a>
        <a class="pw-button-post-share"></a>		
      </div>
      <script src="<%='http://i.po.st/static/v3/post-widget.js#publisherKey=' + (Rails.env.production? ? ENV['POST_KEY'] : 'abc') + '&retina=true' %>" type="text/javascript"></script>
    </p>
    <p>
      Download:
      <%= link_to "CSV", colleges_path(format: "csv") %> |
      <%= link_to "JSON", colleges_path(format: "json") %>
    </p>
    <table id="colleges_table" class='table table-striped table-hover'>
      <thead>
        <tr><th>College(Program)</th><th>Degree</th><th>Country</th><th>State(if USA)</th><th>Location</th><th>Department</th> </tr>
      </thead>
      <tbody>
      <% @schools.each do |school| %>
        <tr>
          <td><%= school.name %> (<%= link_to school.program, school.url, title:school.name+' '+school.degree+' in '+school.program, target:'_new'  %>)</td>
          <td> <%= school.degree %></td>
          <td> <%= school.country %></td>
          <td> <%= school.state %></td>
          <td> <% if school.online %>online<% end %> <% if school.online && school.oncampus %> / <% end %> <% if school.oncampus %>on-campus<% end %> </td>
          <td> <%= school.department %></td>
        </tr>
      <% end %>
      </tbody>
    </table>


    <script>
      $(document).ready( function () {
        $('#colleges_table').DataTable({
            "paging":   false,
            "order": [[2, "desc"], [3,"asc"], [0,"asc"]]
        } );
    } );
    </script>
</div>
</div>